extends SceneTree
const Tracker:=preload("res://scripts/fablewood/music_marker.gd")
func _init()->void:call_deferred("run")
func run()->void:
	var t:=Tracker.new()
	assert(not t.sample(1,0,0,80))
	assert(not t.sample(1,0,79.99,80))
	assert(t.sample(1,0,80.02,80))
	for i:int in 30:assert(not t.sample(1,0,80.02+float(i)*0.01,80))
	assert(not t.sample(1,0,79,80));assert(not t.sample(1,0,80.01,80))
	assert(not t.sample(1,1,0.1,80));assert(not t.sample(1,1,79.99,80));assert(t.sample(1,1,80.01,80))
	assert(not t.sample(2,0,85,80));assert(not t.sample(2,0,85.1,80))
	t.reset();assert(not t.sample(3,0,79,80));assert(not t.sample(3,0,85,80));assert(t.consumed)
	var FX=load("res://scripts/fablewood/music_impact.gd");var fx=FX.new()
	fx.start(Vector2(100,100),false);assert(fx.motes.size()==32)
	for i:int in 120:
		fx.advance(1.0/60.0,false);assert(fx.shake_offset().length()<=2.61)
	fx.advance(1,false);assert(fx.motes.is_empty() and fx.shake_offset()==Vector2.ZERO)
	for i:int in 100:fx.start(Vector2.ZERO,false)
	assert(fx.motes.size()==32)
	fx.advance(0.1,true);assert(fx.shake_offset()==Vector2.ZERO and fx.motes.is_empty())
	fx.start(Vector2.ZERO,true);assert(fx.motes.is_empty());fx.clear();assert(fx.age==fx.DURATION)
	print("MUSIC_MARKER_PASS: exact crossing, once per loop, no seek/stall catch-up, serial reset, 32-mote bound, short capped shake, reduced motion/cleanup")
	quit()
