#!/usr/bin/env python3
"""Flatten this project's small SceneTree test hierarchies for external PCK checks.

The player correctly excludes test/. Godot resolves even relative super-script
paths into res:// while --main-pack is active, so wrappers contain the original
assertions and inherited helpers directly. Original source tests remain canonical.
"""
from pathlib import Path
import argparse,hashlib,re
ROOT=Path(__file__).resolve().parents[1]
CHAINS={
 'ultimate':['fablewood_merge_test.gd','fablewood_ultimate_test.gd'],
 'worldheart':['fablewood_merge_test.gd','fablewood_ultimate_test.gd','fablewood_worldheart_test.gd'],
 'late_enemies':['fablewood_checks.gd','fablewood_late_enemies_test.gd'],
}
DECL=re.compile(r'^(func|const|var)\s+([A-Za-z_]\w*)',re.M)
def flatten(names):
 blocks={};sources=[]
 for depth,name in enumerate(names):
  text=(ROOT/'test'/name).read_text();sources.append(f'{name} SHA256 {hashlib.sha256(text.encode()).hexdigest()}')
  lines=text.splitlines();assert lines[0].startswith('extends ')
  text='\n'.join(lines[1:])+'\n';matches=list(DECL.finditer(text))
  assert matches and not text[:matches[0].start()].strip(),f'Unsupported preamble: {name}'
  for i,match in enumerate(matches):
   kind,identifier=match.groups();key=(kind,identifier)
   block=text[match.start():matches[i+1].start() if i+1<len(matches) else len(text)]
   for method in set(re.findall(r'\bsuper\.([A-Za-z_]\w*)\s*\(',block)):
    previous=blocks.get(('func',method));assert previous,f'Missing super method: {method}'
    alias=f'_pack_super_{depth}_{method}'
    blocks[('func',alias)]=re.sub(r'^func\s+'+re.escape(method)+r'\b','func '+alias,previous,count=1)
    block=re.sub(r'\bsuper\.'+re.escape(method)+r'(?=\s*\()',alias,block)
   assert 'super.' not in block and 'super(' not in block,f'Unsupported super form: {name}'
   blocks[key]=block
 return '# Generated by tools/generate_pack_checks.py; do not edit.\n'+'\n'.join('# '+s for s in sources)+'\nextends SceneTree\n'+''.join(blocks.values())
def main():
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 for label,names in CHAINS.items():
  path=ROOT/'test/pack_checks'/f'{label}.gd';content=flatten(names)
  if args.check:assert path.is_file() and path.read_text()==content,f'Stale wrapper: {path}. Run tools/generate_pack_checks.py.'
  else:path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
 print('PACK_CHECK_WRAPPERS_CURRENT' if args.check else 'Generated 3 equivalent external pack checks')
if __name__=='__main__':main()
